blank_issues_enabled: false
contact_links:
  - name: ❓ Questions / Help
    url: https://github.com/Narash25/20250914_Cold-Approach-App-Starter/discussions
    about: Use Discussions for general questions or help
